### ISSUE TITLE
Including a closed tag

### ISSUE THREAD

**Issue by webchaz** [davidcalhoun/jstoxml#17]
Is it possible to simply include a tag like `<SomeItem />` as oppose to `<SomeItem></SomeItem>` which is what I get when I give an empty string.

Thank you

**Comment by dawsonbotsford** [comment]
Consider adding this code snippet to the README under a tag like "Self closing XML tag" and closing this issue?

**Comment by webchaz** [comment]
Sorry for the lack of reply, Yes that worked we can close, thank you
