### ISSUE TITLE
Publish new release to npm?

### ISSUE THREAD

**Issue by cdhowie** [davidcalhoun/jstoxml#22]
The 0.2.3 version on npm is very old, and includes the issue that causes the `indent` variable to leak (#21).  This has since been fixed in this repository, but the version on npm still has that bug, and it's breaking our unit tests.  Can a new version be published?

**Comment by davidcalhoun** [comment]
Doh, sorry about that.  Just published it, so it should be good to go!  Let me know if there's any issues.
