### ISSUE TITLE
Support for media tags

### ISSUE THREAD

**Issue by AriLFrankel** [davidcalhoun/jstoxml#24]
It would be great for this tool to support media tags: http://www.rssboard.org/media-rss

**Comment by davidcalhoun** [comment]
Thanks for the comment.  It should support everything you need - see the RSS example in the docs: https://github.com/davidcalhoun/jstoxml#example-9-rss-feed

Another example:

```js
jstoxml.toXML({
  _name: 'media:subTitle',
  _attrs: {
    type: 'application/smil',
    lang: 'en-us',
    href: 'http://www.example.org/subtitle.smil'
  }
});
// <media:subTitle type="application/smil" lang="en-us" href="http://www.example.org/subtitle.smil"/>
```

**Comment by davidcalhoun** [comment]
@AriLFrankel Just wondered if that example above helped?  Will close out this issue in a few days.

**Comment by davidcalhoun** [comment]
Closing this out as resolved.  Thanks again for opening it; I hope other folks will find the example helpful.

**Comment by AriLFrankel** [comment]
Sorry for the late response David. I think I don't quite understand what you meant here. I am looking to include images with individual items. This is an example of an item I included in my workaround:
```
     item: {
        category: ...,
        title: ...,
        link: ...,
        description: ...,
        author: ...,
        [`media:content type="image/jpeg" url="${featuredPhotoUrl}"`]: '',
      }
```
This results in <media:content type="image/jpeg" url="..."></media:content type="image/jpeg" url="...">

which breaks when I try to read it in the browser. As a work around I use regex to clean up the closing tag.

**Comment by davidcalhoun** [comment]
Ah I see, yeah that's a little trickier.  This should work:

```js
jstoxml.toXML({
  item: [
    {category: ''},
    {title: ''},
    {link: ''},
    {description: ''},
    {author: ''},
    {
        _name: 'media:content',
        _attrs: {
            type: 'image/jpeg',
            url: '${featuredPhotoUrl}'
        },
        _content: ''
    }
  ]
});
```

Note: remote `content: ''` for a self-closing tag.

**Comment by AriLFrankel** [comment]
👏 👍 This works great! Thanks for your response!

**Comment by davidcalhoun** [comment]
Great!  Good to hear.
