### ISSUE TITLE
Header encoding

### ISSUE THREAD

**Issue by real050280** [davidcalhoun/jstoxml#26]
How do you guys change the encoding of the header?

for example:
`<?xml version="1.0" encoding="iso-8859-1"?>`

Thank you.

**Comment by davidcalhoun** [comment]
Good question!  Looks like I need to update the readme.  Instead of passing a boolean `true` to header, you can pass any custom string:

```js
jstoxml.toXML({
  foo: 'bar',
  foo2: 'bar2'
}, {header: '<?xml version="1.0" encoding="UTF-16" standalone="yes"?>'});

// -> `<?xml version="1.0" encoding="UTF-16" standalone="yes"?><foo>bar</foo><foo2>bar2</foo2>'
```
