### ISSUE TITLE
Creating multiple headers

### ISSUE THREAD

**Issue by real050280** [davidcalhoun/jstoxml#27]
Hello,

Is it possible to create multiple headers like below?

```
<?xml version="1.0" encoding="UTF-8"?>
<?RETRONET TNT="123" TNTVAL="XX"?>
<person>
<fullname>ember dodge</fullname>
</person>
```

**Comment by davidcalhoun** [comment]
Yep, should be possible by passing it in like this:

`<?xml version="1.0" encoding="UTF-8"?>\n<?RETRONET TNT="123" TNTVAL="XX"?>`

E.g.
