### ISSUE TITLE
Handling duplicate tag names

### ISSUE THREAD

**Issue by real050280** [davidcalhoun/jstoxml#28]
Hi guys, I have a requirement where duplicate tag names should be displayed in one parent tag.

for example (input JSON):
```
let input = {
	"toAddress": {
		"street": "Street name first line",
		"street2": "",
		"zip": "70286"
	}
}
```

I handled it like below but it is displaying an empty content instead of displaying both Address lines.
```
{
_name: 'Receiver',
_content: {
	PhysicalAddress: {
	  AddressLine: input['toAddress']['street'],
	  AddressLine: input['toAddress']['street2'],
	  PostalCode: input['toAddress']['zip']
	}
}
```
Results (WRONG):
```
<PhysicalAddress>
   <AddressLine></AddressLine>
   <PostalCode>12345</PostalCode>
</PhysicalAddress>
```

Expected Results:
```
<PhysicalAddress>
   <AddressLine>Street name first line</AddressLine>
   <AddressLine />
   <PostalCode>12345</PostalCode>
</PhysicalAddress>
```

I think, it overwrites the latest value of `<AddressLine>` tag. What is the correct way of doing this ?

**Comment by davidcalhoun** [comment]
That's the expected result because you can't have duplicate keys in JS objects.  Check out the readme for duplicate tags names: https://github.com/davidcalhoun/jstoxml#example-3-duplicate-tag-names

Basically you need to use an array of objects to get the expected result.
