### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by freitasskeeled** [davidcalhoun/jstoxml#30]
Tried to install this package and ./install.sh fails.

Using:
 - Linux Ubuntu
 - Root access using sudo

**Comment by davidcalhoun** [comment]
Thanks for the heads up!  Sorry for the troubles.  I think I'm going to end up just checking in a distro to github to simplify things.

**Comment by davidcalhoun** [comment]
Should be fixed in `1.1.3`
