### ISSUE TITLE
Clarify documentation around browser use

### ISSUE THREAD

**Issue by wbt** [davidcalhoun/jstoxml#37]
Attempting a super-simple example without webpack or rollup, the instructed line 
> // Browser
import { toXML } from 'jstoxml';

produces a `SyntaxError: Unexpected token {` even in Chrome 74, which seems like it should support [native import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). 

Using `<script type="module" src="js/jstoxml.js">` (where that jstoxml.js comes from the `dist` following `npm install`) results in an error `TypeError: Cannot set property 'jstoxml' of undefined at jstoxml.js:11 at jstoxml.js:13`.

Clearer documentation for how to use this package in the browser, explicitly stating any requirements like webpack/rollup, would be an improvement!

**Comment by davidcalhoun** [comment]
Thanks so much for the suggestion!  You're right, the browser example implicitly depended on a module bundler like Webpack.  I updated the docs to reflect that, and also add one more example for the browser global usage, so the readme now covers everything all UMD use cases (commonjs, amd, browser global)
