### ISSUE TITLE
New Line After each tag

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [davidcalhoun/jstoxml#40]
How can I make new line after each tag? For example:
\<a>A Value\</a>
\<b>B Value\</b>
Instead of: \<a>A Value\</a>\<b>B Value\</b>

I'm using "jstoxml": "^1.6.8"

**Comment by davidcalhoun** [comment]
Hi, good question.  I think there may be a small bug in the library right now, this seems like it should output with line breaks when you use the `indent` option, but it's on one line as you describe:

```js
toXML([
  {a: "A Value"},
  {b: "B Value"}
], {indent: '  '});
```

Results in

```xml
<a>A Value</a><b>B Value</b>
```

But seems like it should result in this?  (I'll take a look and see if I can tweak this)

```xml
<a>A Value</a>
<b>B Value</b>
```

You can get line breaks when you nest the value with indenting, e.g.

```js
toXML({
  foo: [
    {a: "A Value"},
    {b: "B Value"}
  ]
}, {indent: '  '});
```

Which results in this:

```xml
<foo>
  <a>A Value</a>
  <b>B Value</b>
</foo>
```

Note that you can also force line breaks between tags with this:

```js
toXML([
  {a: "A Value"},
  '\n',
  {b: "B Value"}
]);
```

Which results in this:

```xml
<a>A Value</a>
<b>B Value</b>
```

**Comment by PhuocHoangMinhNguyen** [comment]
Thanks for replying. I did find a workaround for it when showing the XML file content on the screen, which were entering this line of code into App.css.
div {
  white-space: pre-wrap;
} 
However, I'm not sure if that gonna work when I want to enter the information into an actual XML file and download it (which I don't think it will work). So I am looking forward to receiving more information from you. I will try "force line breaks between tags" for now.

**Comment by davidcalhoun** [comment]
@PhuocHoangMinhNguyen Yep, if you see the new lines with that CSS, then the new line characters should be in the XML file output when you download it as well.

Just a heads up that I added a fix for the original issue.

This code:

```js
toXML([
  {a: "A Value"},
  {b: "B Value"}
], {indent: '  '});
```

or this code:

```js
toXML({
  a: "A Value",
  b: "B Value"
}, {indent: '  '});
```

Will now result in this:

```xml
<a>A Value</a>
<b>B Value</b>
```
