### ISSUE TITLE
Special value to ignore entry

### ISSUE THREAD

**Issue by infojunkie** [davidcalhoun/jstoxml#44]
Thanks for a very useful module!

I'm writing a [fairly complex XML-generation program](https://github.com/infojunkie/ireal-musicxml/blob/main/src/musicxml.js) and there are cases where some attributes/elements may or may not be included, depending on the business logic. Right now, in order to ignore such an entry, I need [to add an explicit condition](https://github.com/infojunkie/ireal-musicxml/blob/main/src/musicxml.js#L191-L211) that only adds the entry in case the condition is satisfied.

A simpler way to code would be to add the entry regardless, and reserve a special value, e.g. `undefined`, to instruct the XML generator to ignore the entry when the special value is found. 

For example, instead of writing:
```
const snippet = [{
  'element1': 'hello',
}];
if (condition) {
  snippet.push({ 'element2': 'goodbye' });
}
```
one could write:
```
const snippet = [{
   'element1': 'hello'
}, {
   'element2': condition ? 'goodbye' : undefined
}];
```

**Comment by davidcalhoun** [comment]
Thanks for using my library!  I believe you could achieve this by passing a function - see [Example #3](https://github.com/davidcalhoun/jstoxml#example-3-simple-functions).  Hope this helps!

**Comment by infojunkie** [comment]
Thanks for you reply. I tried
```
const snippet = [{
   'element1': 'hello'
}, {
   'element2': () => { condition ? 'goodbye' : undefined } // or null
}];
```
but it gave me the same result. Not sure what else could be written using the function. Sorry if I misunderstand!

**Comment by davidcalhoun** [comment]
@infojunkie Just a slight syntax change - try this:

```js
const snippet = [{
   'element1': 'hello'
}, {
   'element2': () => condition ? 'goodbye' : undefined // or null
}];
```

When you use braces, you need to write `return` to return a value, so this will also work:

```js
const snippet = [{
   'element1': 'hello'
}, {
   'element2': () => { return condition ? 'goodbye' : undefined } // or null
}];
```

**Comment by infojunkie** [comment]
Sorry, I had actually forgotten the write the `return` statement when I posted. But with either the `return` block, or with the direct expression, the result is the same:
- When I use `null`, there's a "null" text that gets generated
- When I use `undefined`, there's an empty string that gets generated

My purpose is to ignore the _whole_ entry, not just the value.

**Comment by davidcalhoun** [comment]
I think I see what you're saying.  You can do this in JS like this:

```js
// Positive condition:
toXML([
    {
        element1: 'hello'
    },
    {
        ...(true && {
            element2: 'goodbye'
        })
    }
]);
// -> '<element1>hello</element1><element2>goodbye</element2>'

// Negative condition:
toXML([
    {
        element1: 'hello'
    },
    {
        ...(false && {
            element2: 'goodbye'
        })
    }
]);
// -> '<element1>hello</element1>'
```

**Comment by infojunkie** [comment]
That worked great! Thank you.
