### ISSUE TITLE
XSD validation and linting

### ISSUE THREAD

**Issue by infojunkie** [davidcalhoun/jstoxml#45]
This is a big ask: apologies in advance :sweat_smile: 

In some cases, the XML being generated is supposed to conform to a given XSD. It would be great to validate the generated XML against a given XSD if the latter is passed. 

Furthermore, XSD allows the specification of an [`xs:sequence` that defines the ordering of child elements](https://stackoverflow.com/a/16101786/209184). Since `jstoxml` respects the given order of elements, this means the caller has to ensure that the given order respects the `xs:sequence`. It would be great to re-sort the input elements according to their sequence, if applicable. [Here's an example of how I do it in my code](https://github.com/infojunkie/ireal-musicxml/blob/5c6d7eccea36ca5f80a8aa6b4a2af744f89e2e5b/src/musicxml.js#L89-L105). A generic solution would have to actually get this info from the XSD directly. 

Thanks for reading!

**Comment by davidcalhoun** [comment]
Thanks for the suggestion!  I don't have any plans to implement this into `jstoxml` at the moment, though I can definitely see how it could be useful.  It's sort of out of the scope of this project!
