### ISSUE TITLE
Need a way to add comments to a xml file

### ISSUE THREAD

**Issue by uchihaabhijit** [davidcalhoun/jstoxml#47]
I found this package very useful but is there a way to add comments to a generated xml file??

**Comment by davidcalhoun** [comment]
Thank you for the feedback, that sounds like a reasonable request!  I'll see what it takes to add it when I get a chance.

**Comment by uchihaabhijit** [comment]
@davidcalhoun Thanks. I actually had to write a logic that takes care of it for now but would be better if comments could be inserted during the xml build process. Now I split, concat and then join. Works though!

**Comment by davidcalhoun** [comment]
Comments are now supported with the special `_comment` key!  Check out the [readme](https://github.com/davidcalhoun/jstoxml#example-16-xml-comments) for some examples!
