### ISSUE TITLE
Skip indent for complex xml (or related solution)

### ISSUE THREAD

**Issue by sknox131** [davidcalhoun/jstoxml#56]
I am using your library to write bpmn and need an effective way to write CDATA. Right now, when I output my xml, it puts an indent after a CDATA value. I noticed in the code that there is a flag for marking complex xml values such that if there is an open bracket in the value, then an indent and a newline will be added to the document. Can there be an option to get around this? Possibly an '_xmlIsSimple' xml option? Or potentially some way to create CDATA without writing out the open and close brackets myself?

**Comment by davidcalhoun** [comment]
Thank you for the heads up, will look into this as soon as I can!

**Comment by davidcalhoun** [comment]
Thank you, I believe this is now fixed in v3 for CDATA automatically, please try it out.  Thank you!

**Comment by sknox131** [comment]
Perfect! Thank you!
