### ISSUE TITLE
Explicitly state true for boolean attribute

### ISSUE THREAD

**Issue by sknox131** [davidcalhoun/jstoxml#57]
Could there be an option to explicitly set attributes to "true" if it is a boolean attribute?

**Comment by davidcalhoun** [comment]
Thank you for the heads up, will look into this as soon as I can!

**Comment by davidcalhoun** [comment]
This is now possible in v3 setting the [config option](https://github.com/davidcalhoun/jstoxml#configuration-object-options-passed-as-second-parameter-to-toxml) `attributeExplicitTrue` to `true`.
