### ISSUE TITLE
Null attributes invalidating XML

### ISSUE THREAD

**Issue by iBotPeaches** [davidcalhoun/jstoxml#58]
After peeking this GitHub, I see a 2013 issue here #10 about this. However, in the case I want to describe. We get information from a source we cannot control, sometimes those are null.

![Screen Shot 2022-03-04 at 8 39 35 AM](https://user-images.githubusercontent.com/611784/156773468-1adcde33-5161-4af9-98a5-4141bde92024.png)

This causes the null property to be converted into text, then within the picture of a full XML document is invalid and thus rejected by the server with a vague exception.

Have you reconsidered accepting an option/config to disable this? I notice now vs 2013 you have a config object parameter that is optional, so it could gain a property to opt-in this handling to prevent compatibility issues with clients who prefer this existing behavior.

Thanks!

**Comment by davidcalhoun** [comment]
Thank you for the heads up, will look into this as soon as I can!

**Comment by davidcalhoun** [comment]
You can now achieve this by using the [config option](https://github.com/davidcalhoun/jstoxml#configuration-object-options-passed-as-second-parameter-to-toxml) `attributeFilter` and writing your own supplied filter function to remove attribute entries, e.g.

```js
const content = {
    _name: 'foo',
    _attrs: {
        attr1: 'v1',
        attr2: null
    },
    _content: 'bar'
};
const config = { attributeFilter: (key, val) => val === null };
toXML(content, config);
// -> '<foo attr1="v1">bar</foo>'
```

**Comment by iBotPeaches** [comment]
Very cool thanks for fast turn around. I assume if I just want the nulls left as empty items ie `<test></test>` I don't register any filter?

**Comment by davidcalhoun** [comment]
The default behavior is to output the null value as a string:

```js
const content = {
    _name: 'foo',
    _attrs: {
        attr1: 'v1',
        attr2: null
    },
    _content: 'bar'
};
toXML(content);
// -> '<foo attr1="v1" attr2="null">bar</foo>'
```

Note that `attributeFilter` is just for removing XML attributes of the XML tag.  If this isn't what you intended feel free to reopen this.

**Comment by iBotPeaches** [comment]
Thanks - that looks perfect. Will try out the upgrade on Monday.

**Comment by davidcalhoun** [comment]
@iBotPeaches In your config you forgot to set a filter function for `attributeFilter`.  [See the code sample in the comment above](https://github.com/davidcalhoun/jstoxml/issues/58#issuecomment-1059830075), that will filter out null attributes.

**Comment by davidcalhoun** [comment]
Thank you for the code sample, that helps - I misunderstood your original comment to be about null attributes, not null content.  I'll consider adding a filter for content.

**Comment by davidcalhoun** [comment]
@iBotPeaches Thanks again for the code sample.  In `3.1.0` (just released) I've added a new config function `contentMap` which you can utilize to transform any content, including `null`:

```js
const val = {
    a: {
        foo: 'bar'
    },
    b: null,
    c: true
};

const config = {
    indent: '    ',
    contentMap: (content) => {
        return content === null ? '' : content;
    }
};
toXML(val, config);
/**
Output:
`<a>
    <foo>bar</foo>
</a>
<b/>
<c>true</c>`
*/
```

If you don't want `<b/>` to be self-closed you'll need to use this formatting:

```js
const val = [
    {
        _name: 'a',
        _content: { foo: 'bar' }
    },
    {
        _name: 'b',
        _content: null,
        _selfCloseTag: false
    },
    {
        _name: 'c',
        _content: true
    }
];

const config = {
    indent: '    ',
    contentMap: (content) => {
        return content === null ? '' : content;
    }
};
toXML(val, config);
/**
Output:
`<a>
    <foo>bar</foo>
</a>
<b></b>
<c>true</c>`
*/
```

**Comment by iBotPeaches** [comment]
Worked in testing @davidcalhoun, thanks for quick turnaround. We will go through some testing and get this updated version out to prod soon and see how it handles.

**Comment by davidcalhoun** [comment]
Closing this out, feel free to reopen if needed!
