### ISSUE TITLE
Support for Array

### ISSUE THREAD

**Issue by VerstaenDavy** [davidcalhoun/jstoxml#68]
Hey,

first of all I love your package, the way you handle the reserved characters in XML is just beautiful!

But I do have an issue when converting a JSON that contains an array. In detail I have the following JSON:

`{ "autoFill": [
  {
    "id": 53,
    "description": "Brochure"
  },
  {
    "id": 5,
    "description": "Digital - Booklet"
  }
]}`

and I expect the following XML:

`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<MultiPress>
	<autoFill>
		<id>53</id>
		<description>Brochure</description>
	</autoFill>
	<autoFill>
		<id>5</id>
		<description>Digital - Booklet</description>
	</autoFill>
</MultiPress>`

But I am getting this:

`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<MultiPress>
  <autoFill>
    <id>53</id>
    <description>Brochure</description>
    <id>5</id>
    <description>Digital - Booklet</description>
  </autoFill>
</MultiPress>`

is there anything I am missing here?

**Comment by davidcalhoun** [comment]
You can achieve the output you want with this syntax:

```js
import { toXML } from 'jstoxml';

toXML(
    {
        MultiPress: [
            {
                autofill: {
                    id: 53,
                    description: 'Brochure'
                }
            },
            {
                autofill: {
                    id: 5,
                    description: 'Digital - Booklet'
                }
            }
        ]
    },
    {
        header: '<?xml version="1.0" encoding="UTF-8" standalone="no" ?>'
    }
);

/**
Output:

<?xml version="1.0" encoding="UTF-8" standalone="no" ?><MultiPress><autofill><id>53</id><description>Brochure</description></autofill><autofill><id>5</id><description>Digital - Booklet</description></autofill></MultiPress>

*/

```
