### ISSUE TITLE
_content label doesn't work well -- alway pushed at the end if there are other labels

### ISSUE THREAD

**Issue by Sowwtky** [davidcalhoun/jstoxml#72]
If I have an obj like this:

```
const obj = {
   label: 1
}

const obj2 = { 
    parentTag: {
      _content: obj,
      otherChildContentTagLikeThis: {
        nestedTag1: 'foo',
        nestedTag2: 'bar',
        nestedTag3: 69
    }
  }
}
```

The parsed xml doesn't respect the order of the element I declared. It is parsed as:

```
<parentTag>
      <otherChildContentTagLikeThis>
            <nestedTag1>foo</nestedTag1>
            <nestedTag2>bar</nestedTag2>
            <nestedTag3>69</nestedTag3>
      </otherChildContentTagLikeThis>
      <label>1</label>
</parentTag>
```

Maybe that isn't the pourpose of the _content label but I think that should be fixed in any way.

Another thing, If I try to push the other obj inside the _content label at this point is it parsed as 

```
<parentTag>
  <_content>
      content of the two previous objs
  </_content>  
<parentTag>
```

**Comment by davidcalhoun** [comment]
`_content` isn't intended to have siblings - if you're using the `_content` property then all content should be added there.  Also, worth noting that anytime order matters I recommend using an array instead.
