### ISSUE TITLE
Newlines not possible without indent

### ISSUE THREAD

**Issue by BGSchaap** [davidcalhoun/jstoxml#76]
Currently it is not possible to add newlines after each tag when using an empty string as indent.

Suggestion: replace
https://github.com/davidcalhoun/jstoxml/blob/7c85e0c321da2c3abd5c99783b2854f0e747294d/jstoxml.js#L216
with
`const preIndentStr = (typeof indent === DATA_TYPES.STRING) && !isOutputStart ? '\n' : ''; `

**Comment by davidcalhoun** [comment]
Thank you for the heads up, I'll fix this when I get a chance.  PRs accepted as well!

**Comment by gabrielgatu** [comment]
Hi!

The PR allows to format the output on new lines but it doesn't show how to respect indentation as well: if you add just 

```javascript
{
    indent: "", // or "\n"
}
```

it breaks into newlines but no indentation.

I'm leaving my solution here in case anyone needs it:

```javascript
// Breaks into newlines and keeps indentation
const xml = toXML(data, {
    indent: "\n    ",
})

// Furthermore it eliminates empty newlines (ex: \n\n)
const formattedXML = xml.split("\n")
      .filter(line => line.trim().length > 0)
      .join("\n")
```
